services:
  app:
    container_name: star-wars-api
    image: anunez96/star-wars-api:1.0.0
    ports:
      - "8080:8080"
    environment:
      - SERVICE_URL=ec2-13-59-27-108.us-east-2.compute.amazonaws.com
      - DATABASE_IP=postgres
    depends_on:
      - postgres
    networks:
      - app-network
  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /data/postgres
      POSTGRES_DB: star_wars
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge

volumes:
  postgres:
