services:
  app:
    container_name: star-wars-api
    image: anunez96/star-wars-api:1.0.0
    ports:
      - "8080:8080"
    environment:
      - SERVICE_URL=13.59.27.108
      - DATABASE_IP=postgres
      - JWT_SECRET_KEY=6A7D4E6B5A7234753778214125442A462D4B6150645367566C59703373367639
      - JWT_EXPIRATION_TIME=1800000
    depends_on:
      - postgres
    networks:
      - app-network
  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /data/postgres
      POSTGRES_DB: star_wars
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge

volumes:
  postgres:
