version: v1
spring:
  application:
    name: star-wars-api
  server:
    port: 8080
  swagger:
    enabled: true
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher
  springdoc:
    swagger-ui:
      enabled: true

  datasource:
    driver-class-name: org.h2.Driver
    username: admin
    password: admin
    url: "jdbc:h2:mem:test;DB_CLOSE_ON_EXIT=FALSE"
    h2:
      console:
        enabled: true
        path: /h2-console
