version: v1
spring:
  application:
    name: star-wars-api
  server:
    port: 8080
  swagger:
    enabled: true
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher
  springdoc:
    swagger-ui:
      enabled: true

  datasource:
    datasource:
    url: jdbc:postgresql://localhost:5432/star_wars
    #jdbc:postgresql://13.59.27.108:5432/star_wars
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

service:
  base:
    url: ${SERVICE_URL}
